using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace JellyfinForRayNeo
{
    public static class JellyfinTitleInitials
    {
        public const string All = "*";
        public const string Other = "#";

        private const int HanStart = 0x4E00;
        private const int HanEndExclusive = 0xA000;
        // Offline primary Mandarin initials keep search deterministic on the glasses.
        private const string HanInitials =
        "YDKQSXHWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSGJGYQZJJFGCCLZZBWDWZJLJPFYYNWJJTMYYZWZHFLYPPQHGCCYYYMJQYXXGJXHSDSJNJJSMHMLZRXYFSNGSYCZQZ" +
        "GGLLYJLMYZSSECYKYYHQWJSSGGYXYQYJTWKDJHYCHMYXJTLXJYQBYXDLDWRRJJWYSRLDZJPCBZJJBRCFSLBCZSTZFXXTHTRQGGBDLYCCSCYMMRFCYQZPWWJJYFCRWFDF" +
        "ZQPYDDWYXKYJAWJFFXJPDFTZYHHYCYSWCCYQSCLCXXWZZXNBGNNXBXLZSQCBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYFZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYS" +
        "XSTKZGLYCKGLYSMZXYALMELDCCXGZYRCXSDLTJZCQKCNNJWHJCZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHJQSPSFXLFPBYQXXXYDCCZYLLLSJXFHJXPJBCFFYABYXBH" +
        "CZBJYCLWLCZGGBTSSMDTJCXPTHYQTGJJSCJFZKJZJQNLZWLSLHDZBWJNCJZYZSQNYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBXHYZCYYJXZCFBZZMJYXXCDCZOTTBZLJWFC" +
        "GSZSXFYRLNYJMBDTHJXSQJCCSBXYYTSYFBJDZTGBCNCLCYZZBSACYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQCCWJBHCTDJJSFXJEJJTLBGXSXJMYJJQPFZAS" +
        "YJNCYDJXKJCDJSZCBARTCCLNJQMWNQNCLLLKBYBZZSYHQCLTWLCCRSHLLZNTYLNEWYZYXCZXXGDKDMTCEDEJTSYYS#DQDFMSD#JLHRWNQLYBGLXHLGTGXBQJDZFYJSJY" +
        "JCJMRNYMGRCJCZGJMZMGXMMRYXKJNYMSGMZJYMKLFXMBDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPQXKTACJDHHZ" +
        "DDDRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQSCKJGCGKDJTJLLZYCXKLQSCGJCLTFPCQCZGWBJDQSDJJBYJHSJDDWGFSJGDKCCCTLLPSPKJ" +
        "GQJHZZLJPLGJGJJTHJJYJZCJMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMCLKMDXXKWYXWSLMLPSJQJCQXYJFJTJDXMXXLLCRQBSYJBGW" +
        "YWXGGBCYXPJTGPEPFGDJGBHBNSFJYZJKJKHXQFGQZKFHYGKHDGLLSDJJXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNDJBSBKBBZKLYLXGWXJJWAQZMYWSJQLCJXXJQWJEQ" +
        "XSCWETLZHLYYYSDZPYQYZCPTLSHTZCFYCYXYLJSDCJJAGYSLCLLYYYSGLRQQELDXZSCCCCADYCJYSFSGBFRSSZQSBXJPSJWSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJLH" +
        "MXMCGXYZHJDCTMHLTXZXYLYMOHYJCLTYFBQQJBFBDFEHTKSQHZYWWCNXXCDWHHWGYJLEGMDQCWGFJHCSNTWYDOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMDQ" +
        "JGZTDPPBFYHZHHJYFDZWKGKZBLDNTSXHQEEGZXYLZMMZYJZGSZXKHKHTXEXXGYLYAPSTHXDWHZYDPXAGKYDXBHNHXKDFJNMYHYLPMGOCSLNZHKXXLBZZLBMLSFBHHGSG" +
        "YYGGBHSCYAJTXWLXTZQCWZYDQDQMMGDQLLSZHLSJZWFJHQSWSCELQAZYNYTLSXTHAZNKZZSDHLACXTWWCSGQQTDDYZBCCHYQZFLXPSLZYGPZSZNGLYDQCBDLXJTCTAJD" +
        "KYWNSYZLJHHDZCWNYYZYOMHYCHHHXHJKZWSXHDNXLYSCQYDPCLYZWMYPBKXYJLKZHTYHAXQSYSHXASMCHKDSCRSWJPWQSGZJLWWSCHS#HSQNHZSNGNDAQTBAALZZMSST" +
        "DQJCJKTSCJAXPLGGXHHGOXZCXPDMMHLDGTYBYSJMXHMRCPLXJZCKZXSHFLQXCCDHXEZFCHZCCDYTCJYXQHLXDHYPJQXNLSYYDZOZJNYXQEZYSJYAYJKYPDGHDDXSPPYZ" +
        "NDLTHRHXYDPCJJHTCXMCTLHBYNYHMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZNXCLCCLYLNZSXZJZZLNNLLWHYQSNJHXYNTTDKYJPYCHHYEGKCTTWLGQRLGGTGTY" +
        "GYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZWGYWGPYDQQZZDQXSKCQNMJJZZBXYQMJRTFBBTKHZKBJDJJKDJJTLBWFZPBTKQTZTGPDGNTPJYFALQMKGXBCCLZF" +
        "HZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBFBYYHXCQGABFQYJJDMLJCSJZLLPCHBSXGJYNDYBYQSPQWJLZKCDDTACCBKZDYZYPJZQSJN" +
        "KKTKNJDJGYEPGTLFYQKASDNTCYHBLGDZHBBYDMJRYGKZYHEYYBCMCDTYFZJJHGCJPLXHLDWXJJKYTCYKSSSMTWCTTQZLZBSZDTWZXGZAGYKTYWXLHLCPBCLLOQMMZSSL" +
        "CMBJCSZZKYDCZXGQJDSMCYTZQQLWZQZXSSBPKDFQMDDZDSDDTDMFHTDYZJAQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMZ" +
        "SYZGCJFBZBSQLFCXXXNXKXWYMSDDYQWGGQMMYHCDZTTFGYYHGSTTTYBYKJDHKYJBELHDYPJQNFXFDQKZHQKZBYJTZBXHFDXBDASWHAWAJLDYJSFHBLDNNDNQJTJNCHXF" +
        "JSRFWHZFMDRFJYHWZPDJKZYJYMFCYZNYNXFBYTFWFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRSYMJGSXWZJSPRYDJSJGXHJJGLJJYNZJJXHGJKYMLPEYYCSYSGQZ" +
        "SWHWLYRJLPXSLCXMFSMWKCCTNXNYNPNJSZHDZEPTXMWYWAYYSYWLXJQZQXZDCLAEELMCPJPCLWBXSQHFWRTFFJTNQJHJQDXHWLBYCCFJLALKYYJLDXHHYCSTDYWNCJTX" +
        "YWDRMDRQHWQCMFJDYZMHMAYXJWMYZQSXTLMRSPWWCHAJBXTGCYPXYYRRCLMPAMGKQJSZYJRMYJSNXTPLNBAPPYPYLXMYZKYNLDGYJZCZHNLMZHHANQMPGWQTZMXXMLLH" +
        "GDZXYHXKRXYCJMFFXYHJFSBSSQLHXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJNLQYSHQMLLYZLZJJJKYMZCSFBZXXMSTBJGNXYZHLSNMCQSCYZNFZLXBRNNNYL" +
        "MNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTSXGCQGXZZBHYXJSCRHMKKBSCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCJGQHWLSNZSWXKHLJHYYBQCBFCDSXDLDS" +
        "PFZFSKJJZWZXSDDXJSEEEGJSCSSMGCLXXKYWYLLYMWWWGYDKZJGGGTGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXWMELPTFSXTLLXCLJXJJLJSXCTNSWXLEHHLYQRWHSY" +
        "CSQRYBYAYWJEJQFWQCQQCJQGXALDBZZYJGKGXPLTQYFXJLTPADKYQHPMATLCPDHKXMTXYBHBLEFXDLEEGQDYMSAWHZMLJTWYQXLYJZLJEEYXBQQFFNLYXRDSCTGJGXYY" +
        "LKLLXQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZKLYMHJJHTSMQWYZLKYYWZCSRKQYQLTDXWCDRJKLWSQZWBDCQYNCJSRSZJLKCDCD" +
        "TLZZZACQQCZDDXYPLXCBQJYLZLLLJDDZJGYJYJZYXNYYYNXJXKXDAZWYRDLJYYYRJLGLLDRXJCYKYWNQCCLDDNYYYKYCKCZHJXCCLGZQJGJWPPCQQJYSBZZXYJXJBXJF" +
        "ZBSBDSFNSFPZXHDWZTDMPPTBLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZHFCBBZMQCFMBCMCJXLGPNJBBXGYHYYJG" +
        "PTZGZMQBQDCGYBJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSCXFJEGLSLLSZBQJJJAKLYLDLYCCTSXMCWFGKKBQXLLLLJYXTYLTYXYTDPJHNHGN" +
        "KBYQNFJYYZBYYESSESSGDYHFHWTCJBSDZJTFDMXHCNJZYMQWSRXJDZJQPDQBBSDJGGFBKJBXDGJHMGWJJJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZTJPZYWCBDLF" +
        "WZCWJDXXHYHLHWCZXJTCZLCDPXDJCZCZLYXJJSJBHFXWPYWXZPTDZZBDCCJHJHMLXBQXXBYLRDDGJRRCTTTGQSCZWMXFYTMWZCWJWXJYWCSKYBZQCCTTQNHXNKXXKHKF" +
        "HTSWOCCJYBCMPZZYJBNNZPBTHHJDLSCDDYTYFJPXYNGFXBYQXCBHXCBSXTYZDMZYSNXSXLHKMZXLTHDHKGHXJSSHQYHHCJYXGLHZXCSNHEKDTGQXQYPKDHEXTYKCNYMY" +
        "YYPKQYYTJXZLTHHQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHHXCXWHESZJYDJCCDBQCDGDNYXZDHCQRXCBMZT" +
        "QCBXWGQWYYBXHMBYMYKDYECMQKYAQYNGYZSLFYKKQGYSSQYSHJGJCNXKZYCXSBKYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMQSYQKDZLJQQYP" +
        "LCYCZTCQQPBBQJZCLPKHQCYYXXDTDDDSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJCKXYAMYLSJHMLALYKXCYYDMAMDQMLMCZNNYYBZKKYFLMCHCMLHXRCJJHSY" +
        "LNMTJGGZGYWJXSRXCWJGJQHQZDQJDZJJZKJKGDZQGJJYJYLHZXXCDQHHHESTMHLFSBDJSYYSHFYSSCZQLPBDRFRZTZDKYKGSCTGKWDQZRKMSYNBCRXQBJYFAXPZZEDZC" +
        "JYKBCJWHYJBQDZYWNYSZPTDKZPFPBAZTKLQYHBBZPNBPTYZZYBHNYDCPJMMCYCQMCJFZZDCMNLFPBPLNGQJTBTTAJZPZBBDNJKLJQYLNBZQHKSJZNGGQSCZKYXCHPZSN" +
        "BCGZKDDZQANZGJKDNTLZLDWJLJZLYWTXNDJZJHXYATNCBGTZCSSKMNJPJYTSRWXCFJWJJTKHTZPLBHSNJZSYJBWBZYZLSTLSBJHDWWQPSLMMFBJDWAJYZCCJTBNNRZWQ" +
        "XCDSLQGDSDPDZHJTQQPSQLYYJZLGYHSZLCTCBJTKTYCZJTQKBPJLGMJZDMCSGPYNJZJJYYKNHRPWSZXMTNCSZZYXYBYHYZAXYWKCJTLLCKJJTJHGCXDXYQYCZBYWBLWQ" +
        "CGLZGJGQRQCCZSSBCRBCSKYDZNLJSQGXSSJMECNSTZTPBDLTHZWHQWQTZEXNQCZGWESKSSBYBSTSCSJCCGBFSDQSZLCCGLLLZGHZCTHCNMJGYZAZNMCKCSTJMMZCKBJY" +
        "GQLJYJPPLDXRGZYXCCSNHSHGDZNLZHZJJCDDCBCJFLBFQBCZZWPQDNHXLJCTHQWJGYLNLSZZPCJDSCQQHJQKDXKPBAJYEMSMJTZDXLCJYRYYNWJBNGZZKMJXLTBSLLRT" +
        "PYLCSZNXJHLLHYLLQQZQLXYMRCWCXSLJMCZLTZLDWDJJLLNZGGQXPPSKYGYGGBFZPDKMWGHCXMCGDXJMCJSDYCABXJDLNBCDDYGSKYDJTXDJJYXMSAQAZDZFSLQXYJSJ" +
        "ZYLBLXXWXQQZBJZLFBBLYLWDSLJHXJYZJWTDJCYFQZQZZDCSXZZQLZCDZFCHYSPYMPQZMLPPLFFXJJNZZYLSJYYQZFPFZKSYWJJJHRDJZZXTXXGLGHTDXCSKYSWMMTCW" +
        "YBAZBJKSHFHGCXMHFQHYXXYZFTSJYZBXYXPZLCHMZMBXHZZSSYFDMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXCSBZZWWHHCWTZZZPJXSNXQQJGZYZAWLLC" +
        "WXZFXGYXYHXMKYYSWSQMNJNAYCYSPMJKGWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDLYHLXRLNLLSTYZYYQYGYHHSCCSMCCT" +
        "ZCXHYQFPYYRPFFLFQTNTSZLLZMHWTCJQYZWTLLMLMDWMBZSSMZRBPDDDLGJJBXCCSRZQQYGWCSXFWZLXCCRBTDZMCYGGDLQSGTJMWLJMYMMSYHFBJDGYXCCPSHXCZCSB" +
        "SJWJGJMPBWAFFYFNXHYDXZYLREMZGZCYHSSZDLLJCSQFZXXKPTXZGXJJGBMYYYSNBDYLBNLHBFZDCYFBMGQRRMSSZXYSGTZNNYDZZCDGBJAFJBDKNZBLCSSCPSGZYCJS" +
        "ZLMLRZZBZZLDLSLLYSXSQZQLYXZLSGKBRXBRBZCYCXZJZEEYFGKLZLYYHGYSGZLFJHGTGWKRAAJYZKZQTSSHJJXDZYZ#YJLZYRZDQQHGJZXSSZBTKJPBFRTJXLLFQWJG" +
        "SLQTYMBLPZDXTZAGBDHZZRBGJHWNJTJXLHSCFSMWLLDQYSJTXKZSCFWJLBXFTZLLJZLLQBLCQMQQCGCDFPBBHZCZJLPYYGJDTGWDCFCZQYYYQYSRCLQZFKLZZZGFFSQN" +
        "WGLHJYCJJCZLQZCYJBJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCJCYHZWPBYHXRYLYBHKJKSFXTZJMMCHHLLTNYYMSXXYZPYJJYCDYZWMTJJKQYRHLLQX" +
        "PSGTLWYCLJSCBXJYZFNMLRGJJTYZBSYZMSJYJHGFZQMSYXRSZCWTLRTQZSSTKXGQGGSPTGCDNJSGCQCQHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSCPYHJHHGNYGKGGCMJ" +
        "DZLLCCLXQSFTGZSLLLMLCSKCTBLJZZSZMMNYTPZSXQHJCJYQXYEXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSDCTMJCSJJDHJNXTNRZTZFQRHQGLLGCXSZSJDJLJCYTSJ" +
        "TLNYXHSZXCGJZYQPYLFHDJSBPCCZGJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYNQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYLFZSLJCQZLYLZCJESHNYLLJXGJXLYJYYY" +
        "XNBCLJSSWCQQCJYLLCLDJYLLZLLBNYLGQCHXYYQOXCCQKYJXXHYKLKSXAYQCCQKKKKCSGYXXYQXYGWTJOHTHXPXXCSSHCYEYCHZZCBWQBBWJQCSCSZSSLZYLGDESJZMM" +
        "YMCYTSDSXXSCJPQQSQYLYFZYCHDJDZYWCBTJSYDJHCYDDJLBDJJSODZYQYSQKXXDHHGQJYOHDYXWGMMMAJDYBBBPPBCMHCPLJZSMTXERXJMHQDSTPJDCBSSMSSSTHJTS" +
        "LMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQQYXHYAYKQYDDLQYYYSSZBYDSLNTFGTZQBZMCHDHCZCWFDXTMQQSPHQWWXSRGJCWTJTZZQMGWJJRJHTQJBBGWZFXJHNQFX" +
        "XQYWYYHYSCDYDHHQMNMDMMCPBSZPPZZGLMZFOLLCFWHMMSJZTTTHLMYFFYTZZGZYSKJJXQYJZQPHMBZZLYGHGFMSHPCFZSNCLPBQSNJSZSLXJFPMTYJYGBXLLDLXPZJY" +
        "PJYHHZCYWHJYLSJEXFSSZYWXKZJLLADTMLYMQJPWXXHXSKTQJEZRPXXZGHMHWQPWQLYJJQJJZSZCFHJLCHHNXJLQWZJHBMZYXBDHHYPYLHLHLGFWLCFYYTLHJJCJMSCP" +
        "XSTKPNHJXSNTYXXTESTJCTLSSLSTDLLLWWYHDHRJZSFGXSSYCZYKWHTDHWJSLHTZDQDJZXXQGGYLTZPHCSQFZLNJTCLZPFSTPDYNYLGMJLLYCQHYNSBCHYLHQYQTMZYB" +
        "BYWRFQYKJSYSLZDYJMPXYYSSRHZJNYQTQDFZBWWDWWRXCWHGYHXMKMYYYHMSMZHNGCEPMLQQMTCWCTMHMXJPJJHFXYYZSJZHTYBMSTSYJDTJJQYTLHYNBYQZLCXCNZWS" +
        "MYLKFJXLWGBYPJYTYSYLYMZCKTTWLGSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPCCPWCMGDHHXZDZXFJHGZTTSBJHGYGLZYSMYCLLLYBTYXHBBZJKSSDMALHHYCFYGM" +
        "QYPJYCQXJLLLJGCLZGQLYCJCCTOTYXMTMSHLLWCGFXYMZMKLPSZZZXHHJYSLCTYJCYHXSGYXZKXLZWPYJPDHJWPJPWSQQXLXXDHMRSLZCYZWSTCXKYSTZSHBSCCSTPLW" +
        "SSCJCHJLCGCHSSPHYLHFHHXJSXYLLNYLMZDHZXYLSXLWZYHCLDYAHZCMDDYSPJTQJZLNGJFSJSHCTSDSZLBLMSSMNYYMJQBJHRCWTYYDCHQLJAPZWBGQYBKFCMJWLZLL" +
        "YYLSZYDWHXPSBCMLJPSCGBHXLQHYRLJXYSWXHXZLLDFHLSLYMJLJYFLYJYCDRJLFSYZFSLLCQYQFGJYHYSZLYLMSTDJCYHBZLLNWLXXYGYYHBMGDHXXHHLZZJZXCZZZC" +
        "YQZFNJWPYLCPKPYKPMCLGKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTJXHQLHYXXXYWZYSWTMZKHLXZXZPYHGCHKJFSYH#TJRLXFJXPTZTWHPLYXFCR" +
        "HXSHXKJXXYHZJDXJWYLHYHMJDBFLKHTXCWHCFWJCFPQRXQXCYYYJYGRPXGSCSXNGWCHKZDXHFLXXHJJBYZWTSXNNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSEB" +
        "HXXWXYHHXYXNSQYXMLYWRGYQLXBBCLJSYLPSYTJZYHYZAWLHORJMKSCZJXXXYXCHCYTRYXQJDDSJFSLYLTSFFYXLMTYJMJJYYYXLTZCSXQZLHZXLWYXZHDNLRXHXJCDY" +
        "HLBRLMBRLLAXKSLLLJLYXXLYCRYLCJCGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSEPCKZDQYQPBPCJPDCYZBDBBCYYDYCNNPJMTMLRMFMMGWYGBSJGYGSMDQQQZTXMKQWG" +
        "XLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWKCQQBFQJCZAGZGMYKBHYYHZYKNDKZMBPJYSPXTHLFPNYYGXJDBKXNHHJHZJXSTRSTLDXSKZYSYBMXJLXYSLBZY" +
        "SLHXJPFXBQNBYLLJQKYGZMCYZZYMCCSLDLHZGWFWYXZMWCXTYNXJHBYYMCYSBMHYSMYDYSHQYZCHMJJMZCAAHCBJBBHPLXTYLSXSDJGJDHKXXTXXNBHNMLNGSLTXMRHN" +
        "LXQJXMZLLYSWQGDLBJHDCGJYQYCMHWFWJYBBBYJMJWJMDPWHXQLDYAPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWECDWWCJMBTXC" +
        "HXYQXLLXFLYXLLJLSSFWDPZSMYJCLMSWTCZBCHQEKCQBWLCGYDBLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZCLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGZQCJZYABSCKZCJY" +
        "CCQLJSQXALMZYYYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTHHSSTCYJLBSWZLXZXRWGLDLZRLZQTGSLLLLZLYMXQGDZHGBDBHZPBRLW#XQBPFDWO##WHLYPCBJCC#DMB" +
        "ZPBZZ#CYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPTHTZZMBBLXLCMYFFGTJJQWFTMDPJWDNLBZCMMCTGBDZLQLPYFHSYMJYLSDCHDZJWJCCTLJ" +
        "CLDTLJJCPDDPJDSSZYNNDBJLGGJZXSXNLYCYBJJQXCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJWHTYCZHYMDJXTTMPXSFLZCDWSLSHXYBZGTFMLCJTACBBMGDEW" +
        "YCYZCDSZCYHFLYCTYGWHKJYYLSJCXGYWJCBHLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFLLQLLXFDYHABXGGNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBBGBFDFBBQ" +
        "JZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZGZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXJPGALXZDAGLMDGXMWZQYTXDXXPFDM" +
        "MSSYMPFMDMMKXKSYZYSHDZKJSYSMMZZZMSYDNZZCZXBMLSTMDDNMXCKJMZTYYMZMZZMSSHHDCCJEMXXKLJSTGWLSQLYJZLLSJSSDBPMHNLYJCZYHMXXHGZCJMDHXTKGR" +
        "MXFWMCKMWKDCKSXQMMMFZZYDKMSCLCMPCGMWRPXQPZDSSLCXKYXTMLGJYAHZJGZQMCSNXYHMMPMLKJXMHLMLGMXCTKZMJJYSZJSYSZHSYJZJCDAJZYBSDQJZGWZKGXFK" +
        "DMSDJLFMEHKZQKJBEYPZYSZCDWYJFFMZJYKTTDZZEFMZLBNPPLPLPBPSZALLTYLKCKQZKGENQLWAGXXYDPXLHSXQQWQYKXQCLHYXXMLYCCWLYMQYSKYCHLCJNSZKPYZK" +
        "CQZQLJBDMDJHLASQLBYDWQLWDNBQCRYDDDTJYBKBWSZDXDTNPJDTCTQDFXQQMGNSECLSTBHPWSLCTXXLPWYDZKLZYGZCQAPLLKCCYLBQMQCZQCLJSLQZDJXLDTHPZQDL" +
        "JJXZQDJYZHKZLJCYQDYJPPYPEAKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXQQZBDZRYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLL" +
        "BJDZLCBZHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXJSCDGSLNMDLRYTZLRYYLXQHTXSRTZCGYXBNQQZFHYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZHHYZZJRDYZHNF" +
        "XGLFXSLKGJTCTSSYLLGZRZBBJZZKLPKBCZYSLXYXBJFPNJZZXCDWXZYJXZZDJJGGGRSRJKMCMZJLSJYWQSHYHQJSXPJZZZLSNSHRNYPJTWCHKLBSRZLCXWJQXQKYSJYC" +
        "ZTLQZYBBYBWZJQDWGYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDJLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLLBJJZBSJHTSJDYSJQJPDLZCDCWJKJZZLPYCG" +
        "MZWDJJBSJQZSYZYHHXCBBJYDSSDDZNCGLQMBTSFCBFDZDLZNFGFJGFSMPTJQLMBLGQCYYXBQKDXJQSRFKZTJDHCZKLBSDZCFYTPLLJGJHTXZCSSZZXSTCYGKGCKGYOQX" +
        "JPLZBBBGTGYJDGCZQSZLBJLSJFZGKQQJCGYCZBZQTLDXRJXBSXXPZXHYZYCLWDSJJHXMFCZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBDCYPCZPPDYMT" +
        "ZSGYHCKCPZJGSLCLNSCDSLDZXBMSDLDDFJMKDJDHSLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNCJYQTZZFSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNC" +
        "ZQZBBWSKRFBCYZMTHBLGJPMCZZCSTLXSHTZCYZLZBLFEQHLXFLCJLYLJQCBZLZJGHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSZXNTNLZDNTLMSJXGZJY" +
        "JCZXYHYHWRWWQNZTNFJSCPZSHZJFYRDJSFSCJZBJFZQZCHZLXFXSBZQLZSGYFTZDCSZXZJBQMSZKJRHXJZCGBJKHCHGTJKJQGLXBXFGDRTYLXJXGDTSJXHJZJJCMZLCQ" +
        "SBTXHQGXTTXHXFTSDKFJHZYJFJXRZCDLLLCQSQQZQWQXSWQTWGWBZCGCLLQZBCLMQQTZGZXZXLJFRMYZFLXYSQXXJKXRMJDCDMMYXBSQBHGCMWFWTGMXLZBYYTGZYCCD" +
        "XYZXSWGXYJYZNBGPZJCQSYXCXRTFYCGRHZTXSZZTHCBFCLSYXZLJQMZLMPLMXZJSSFLBYSMYQHXJSXRXSQZZZSSLYFLCZJRCRXHHZXQYDSHXSJJHZCXJBDYNSYSXJBQL" +
        "PXZQPYMLXZKYXLXCJLCYCRXZZLLDLLLSJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWL" +
        "ZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFCGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWWGWHLLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLBFLCWBJZC" +
        "LJJMZLPJJLYMQDMYYYFBGYGQZGLYZDXQYXRQQQHSXYYQQYGJTYXFSFSLLGNQCYGYCWFHCCCFXBYLYPLLZQXXXXXKQHHXSHJDCFDSCZJXCPZWHHHHHAPYLHALPQAFYHXD" +
        "YLLKMZQGGGDDESRNNDLTZGCHYBPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZPNDZCLZYWLLZNTEYTGXLHSLPJJBDGWXPCDNTJCKLKCLWKLLCASSTKNZDNQNTTLY" +
        "YZSSYSSZZRYLJQKCGBHHCRXRZYDGRGCWCGZHFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBQTBGTZFZNPZFPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDCJXXEAHPNZG" +
        "CTZCMXCXMMJXNKSZQNMNLWBWWXJJYHCLSTMCSQDJCXXTPCNPDTNNPGLLLZCJLSPBLPLKCDTNJNLYYRSCFFJFQWDPGZDWMNZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTT" +
        "BQLWSTSZGYBLJPXGLBOCLGPCBJFTMXZLJYLZXCLTPNCLCGXTFZJSHCRXSFYSZDKNTLBYJCYJLLSTGQCBXNWZXBXKLYLHZLQZLNZCQWGZLGZJNCJGCMNZZGJDZXTZJXYC" +
        "YYCXXJYYXJJXSSSJSTSSTTPPGHTCSXWZDCSYFPTFBCHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTYWBMNJHSKBMDDBCYSCCLDXYCDDQLYJJHMQLLCSGLJJSYFPYYCCYLTJAN" +
        "TJJPWYCMMGQYYSQDHQMZHSZXPFTWWZQSWQRFKJLXJQQYFBRXJHHFWJGZYQACMYFRHCYYBYQWLPEXCCZSTYRLTSDMQLYKMBBGMYYJPRKNNBBSXYXBHYZDJDNGHPMFSGBW" +
        "FZMFJMMBCMZZCJJLCNYXYQGMLRYGQCCYHZLWJGCJCGGMCJJFYZZJHYCFRRCMTZQZXHFQGDJXCCJEAQCRJTHPLJLSZDJRBCQHJDZRHXLYXJSYMHZYDWLDFRYHBBYDTSSC" +
        "CWBXGLPZMLZZTQSSCPJMMXJCSJYTYCGHYCJWSNSXLFEMWJNMKLLSWTXHYYYGCMMCWJDQDJZGLLJWJNKHPZGGFLCCSCZMCBLTBHBQJXQDJPDJQTGHGLFQAWBZYJJLTSTD" +
        "HQHCTCBCHFLQMPWDSHYYTQWCNZTJTLBYPBPDYYYXSQKXWYYFLXXNCWCXYBMAELYKKJMZZZBRXYAQJFLJPFHHHYTZZXRGQQMHSPGDZJWBWPJHZJDYSCQWZKTHXSQLZYYM" +
        "YSDZGRXCKKHJLWPYSYSCSYZLRMLQSYLJXBCXTLHDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBYGBZGZTCPLDJLSLYLYMDTMTCPALCXPQJCJWTCYYZLBLX" +
        "BZLQMYLJBGHDSLSSDMXMBDCZSXWHAMLCZCPJMCNHJYJNSYGCHSKQMZZQDLLKABLWJQSFMOCDXJRRLYQCHJMYBYQLRHETFJZFRFKSRYXFJDWDSXXLWSQJYSLYXWJHSNLX" +
        "YYXHBHAWHHJCXWMYLJCSQLKYDTTXBZSXFDXGXSJHHSXXYBSSXDPWNCMRPTJZCZENYGCXQFJXKJBDMLJCMQQXLOXSLYXXLYLLJDZBTYMHBFSTTQQWLHOGYBLSCALZXQLH" +
        "TWRRQHLSTMYPYXJJXMQSJPNBRYXYJLLYQYLTHYLQYFMHKLJDMLLHFZWKZHLJMLHLJKLJSTLQXYLMBHHLNLSXQCHXCFXXLHYHJJGBYZZKBXSCQDJQDSXJZSYHZHHMGSXC" +
        "SYMXFEBCQWWRBPYYJQTYQCYJHQQZYHMWFFHGZFRJFCDBXNDQYZPCYHHJLFRZGPPXZDBBGZQSTLGDGYLCQMGCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJTCBEH" +
        "SXFSSFXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQSXLLDTTKHHYBFPWDYYSQQRNQWLGWDEBDWCYYGCDLKJXTMXMYJSXHYBRWFYMWFRXYQMXYSCTZZTFYKMLDHQDLWYQNLCRY" +
        "JBLPSXCXYWLSBRRJWXHQYBHTYDNHHGMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXWZZMMGLMXCLMXCZMXMZSQTZPPJQBLPGXJZHFLJJHYCJSNXWCXSCCDLXSYJDCQ" +
        "CXSLQYCLZXLZZXMXQRJMHRHZJPHMFLJLMLCLQNLDXZLLLFYPNGJYSXCQQDCMQJZZXHNPNXZMEKMXXYKYQLXSXTXJXYHWDCWDZHQYYBGYBCYSCFGFSJNZDYZZJZXRZRQJ" +
        "JYMCANHRJTLDBPYZBSTJHXXZYPBDWFGZZRPYMTNGXZQBYXMBBFCCKRJJJBJEGRZGYCLKXZDXKKNSJKCLJSPGYYZLQQJYBZSSQLLLKJFCBKTYLCCCDBLSPPFYLGYDTZJY" +
        "QGGKQTTFCXBDKDXXHYBBFYTYHBCLPDYTGDHRYRNJSBTCSNYJQHKLLLZSLYDXXWBCJQSBXBFJZJCJDZFBXXBRMLAZGCSNCLBJDSTBLFRZDSWSBXBCLLXXLZDJZSJPYLYX" +
        "XYFTFFFBHJJJGBYGJPMMMMSSCLJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSDGJGYGMSCLJJXDTYGJQJQJCJZCJGDZDSHQGSJGGCJHQXSNJLZZBXHSGZXCXYLJXYX" +
        "YYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYXJXNCYZXFXCSYSZXYYSCHSHXZZZGZZZGFJDLDYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSCXSHCGGQHJHGXWSZTMZMEHYXG" +
        "EBTYLZKKWYTJZRCLEKESTDBCYKQQSAYXCJXWWGSBHJSZSDHCSJKQCXSWXFCTYNYDPZCCZJQTZWJQDZZZQZLJCHLSBHPYDXPSXSHHEZDXFPTJQYZZXHYAXNCFZYYHXGNQ" +
        "MYWXTZSJPKHHGYMXMXQCXTSBCQSJYXHTYYLYBCQLMMSZMJZJLLCOGXZAAJZYHJMCHHCXZSXZDZNLEYJJZJBHZWZZSQTZPSXZTDSXJJJZNYAZPHHYYSRNQDTHZHAYJYJH" +
        "DZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKW" +
        "YSSDCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHHXXHLHDLDJQSLDWBSXFZZYYSCHTYTYJBHECXHJKGJFXBHYZJFXBWHBDZFYZBCAPNPG" +
        "NYDMSXHKHHMAMLNBYJTMPXYJMCTHJBZYFCGTYHWPHFTGZZEZSBZEGPBMDSKFTYCMHBLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZL" +
        "YBCWZZBYZDZYPSWYJGXZBDSYSXLGZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNTXCHCZXTZZLJFZGQSQYXZJQC" +
        "CCCDJCDXZJYQJCCGXZTDLGSCXZSYJJQTCCLQDQZTQCHQQJZTEZZZPBKKDJFCJFZTYBQYQTTYNLMBDKTJCPQZJDZFPJSBNJLGYJDXJDZQKZGQKXCLPZJTCJDQBXDJJJST" +
        "CJNXBXCMSLYJCQMTJQWWCJJNJNLLLHJCWQTBZQYCZCZPZZDZYDDCYZDZCCJGTJFZDPRNTCTJDCQTQNDTJNPLZBCLLCTDSXKJZQDPZLBZNBTJDCXFCZDBCCJJLTQJPLDC" +
        "GZDBBZJCQDCJWYNLLZLZCCDWLLXWZLXRSNTQJCCXKJLSGDFQTDDGLRLAJJTKLYMKQLLDZYTDYYCYGJWYXDXFRSKSTCDENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKYZSP" +
        "EGJJGLKQZZZSLYSYWYZWFQZNLZZLZHWCGKYPQGNPGBLPLRRJYXCCCGYHSFZFWBZYWTGZXYLJCZWHXZJZBLFFLGSKHYJZEYJHLPLLLLCYGXDRZELRHGKLZZYHZLYQSZZJ" +
        "ZQLJZFLNBHGWLCZCFJWSPYXNLZLXGCCPZBLLCXBBBBXBBCBBCRNNCCCYRBBSYLDCGQYYQXYGMQZWTZYDYJHYFWDEHZDJYWLCCNTZYJJCDEDPZDZTSTQJHDYMBJNYJZLX" +
        "TSSTPHNDJXXBYXQTZQDDTJTDYZTGWSCSZQFLSHLGLBCJBHDLYZJYCKWTYDYLBNYDSDSYCCTYSZYYEBGEXHQDDWNYGYCLXTDCYSTQMYGZASCCSZZDDLCCLZRQXYYELJSB" +
        "YMXSHZTEMBBLLYYLLYTDQYSHYMRQXKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYGHQZJHHXJXGNLJKZLYYCDXLFWFGHLJGJYBXBLYBXQPQGZTZPLNCYBXDJYQYDYM" +
        "RBESJYYHKXXSTMXRCZZYWXYHYBMCFLYZHQYZMQXDBXBZWZMSLPDMYCKFMZKLZCYJYCCLHXFZLYDQZPZYGYJYZMZXDZFYFYTTQTCHGSPCZMLCCYTZXJCYTJMKSLPZHYSN" +
        "WLLYTPZCTZZCKTXDHXXTQCYPKSMQCCYYAZHTJPCYLZLYJBJXTFNYLJYYNRXCYLMMNXJSMYBCSYSSLZYLLJJGYLDZDPQBFZZBLFNDSQKCZFHHHGQMRDSXYCSTXNQQJPYJ" +
        "BFCXDYQFBNXEJDGYQBSRCNFYYQPGHYJDYZXGRHTKYLEQDZNTSMGKLBSGBPYSZBYTJZSSZJCSSXZBHBSCSBZCZPTQFZMQFLYPYBBJGSZMXXDJMTHYSKKBJTXHJCEGBSMJ" +
        "YJZCXTMLJYXRZZQSCXXQPTZXMKYXXXJCLJPRMYYGADYSKQLSADHRSKQXZXZTCGHZTLMLWXYBWSYCDBHJHCFCWZSXHYTKZLXQSHLYCZJXEMPLPRCGLTBZZTLZJCYJGDTC" +
        "LGLPLLQPJMZPAPXYZLAKTKDNCZZBNZCTDQQZJYJGMCTXLTGCSZLMLHBGLKFWNWZHDXPHLFMKYDLGXDTWZFRJEJCTZHYDXYKSHWFZCQSHKTMQQHTCHYMJDJSKHXZJZBZZ" +
        "XYMPAJQMSDBXLSKLYYNWRTSQLSCBPDBSGZWYHTLKSSSWHZZLYYTNXJGMJSZSXFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZJCLXXKSBZQCLHJPHQPLSXSC" +
        "KSLNHPSFQQYTXJJZLQLDXZJJZDYYDJNZPTFCDSKJFSLJHYLZQJZLBTHYDGDJFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDSCLBBLXKLELXJLBJYCXJXGCNLCQPLZLZ" +
        "NJTZLJGYZDZPLTQCSSFDMNYCXGBTJDCZNBGBQYQJWGKFHTNBYQZQGBKPBBYZMTJDYTBLSQMBSXTBNPDXKLEMYYCJYNZDTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPWLTLK" +
        "XSLZCGGEXCLFXLKJRTLQJAQZNCMBQDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLHZLYCBLCXZCJADQLMZ" +
        "MMSSHMYBHBSKKBHRSXXJMXSDZNZPXLBBRAGGGFCHGMSKLLTSJYYCQLCSKYWYEHYWHBHQYWBAWYKQLDQFTNTKHQCGDQKTGPKXHCPDHTWTMSSYHBWCRWXHJMKMZNGWTMLK" +
        "FGHKJYLDYYCXWHYECLQHKQHTDQHHFFLDXQWGZYYDESBPKYRZPJFYYZJCEQDZZDLATTBBFJLLCXDLMJSDXEGYGSJQXCFBXSSZPDYZCXDNYXPFZYDLYJCCPLTXLSXYZYRX" +
        "CYYSDYLWWNDSAHJSYGYHGYWKAXTJZDAXYSRLTDJSSAXFNEJDXYZHLXLLLZHZSJNYQYQQXYJGHZGJCYJCHZLYCDSHWSGCZYJXCLLNXZJJYYXNFSMWFPYLCYLLABWDDHWD" +
        "XJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWFXJMMMLLHAFDLLAFLBHHHBQQJTZJCQJJDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNMZDBYY" +
        "TBJHPYBYGTJXAAHGQDQTMYSTQXKBTSBKJLXRBEQQHQMJJBDJWTGTBXPGBKTLGQXJJJCDHXQDWJLWRFMQGWQHCKRYSWGBTGYGBWSDWDWRFHWYTJJXXXJYZYSLPHYYPAYX" +
        "HYDQKXSHXYXESKQHYWBDDDPPLCJLHQEEWXKSYYHDYPLFJTHKJLTCYYHHJTTPLTZZCDLTHQKCXQYSTEEYWKYZYXXYYSDDJKLLPWMCYHQGXYHCRMBXPLLNQYDQHXSXXWGD" +
        "QBSHYLLPJJJTHYJKYPHTHYYKTYEZYENMDSHLCRPQFBGFXZBSBTLGXSJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXTRYJCYFFSYTYZBJTBCTSBSD" +
        "HRTJJBYTCXYJEYLXCBNEBJDSYSYHGSJZBXBYTFZWGENYHHTHJHATFWGCSTBGXKLSTYWMTMBYXJSKZSCDYJRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXHLJXBBDE" +
        "YNJGHXGCKGSCYMBLXJMSZNSKGXFBNBBTHFJAAFXYXFPXMYFHDTZCXZZPXRSYWZDLYBBJTYQWQJPZYPZJZNJPZJLZTFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJ" +
        "ECXALZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTGSQCZLPTXCDYYZSSQZSLXLZMACBCQBZYXHBSXLZDLTCDJTYLZJYYTPZYLLTXJSJXHLBMYTXCQRBLZSSFJZZTNJY" +
        "DXMYJHLHPBLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYATJBBCTDKHQHKGTGPBKQYSLBXBBCKBMLLXDZSTBKLGGQKQLSBKKDFXRMDKBFTPZFRTBBMFERQGXKJPZSS" +
        "TLBZDPSZQZSJTHLJQLZBPMSMMSXLQQNHKNBLRDDNHXDHDDJCYYGYFQGZLGSYGMJQGKHBPMXYXLYTQWLWGCPBMJXCYZYDRJBHTDJXEESHTMJSBYPLWHLZFFNYPMHXQHPL" +
        "TBQPFBCWJDBYGPNXTBFZJGSDDTJSHXEAWZZYLLTTYBWJKGXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHXZLZZBB" +
        "HQZWWYCRDHLYQQJBEYFSGXTHSRXWQHWFSLMSSGZTTYEYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZSSFGLXMXZXFGHKZSZGGYLCLSARJXHSLLLMZXELGLXYDJY" +
        "TLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPJLBXBMMYWXGSLZHGLZGNYFLJBYFDJFRGSFMBYZHQFBWJSY" +
        "FYJJPHZBYYZFFWODGRLMFTMLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYTHLRMGRJXZCLHNELJJTHTBWJYBJJBXJJTJTEEKHWSLJPLPSFAZPQQBDLQJJTYYQLYZKDKS" +
        "QJYYJZLDQCGJJYZJSYCMRAQTHTEJMFCTYHYPKMHYCWJDCFHYYXWSHCTXRLJGJSHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYP" +
        "CLXYJZYZYYPNHMYMDYYLBLHLSYYGQLLNJJYMSOYCBZGDLYXYLCQYXTSZEGXHZGLHWBLJGEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCL" +
        "YCJPCPZJZJMMYLCJLNQLJJJLXXJMLSZLJQLYCMMHCFMMFPQQMFXLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYDYXYQMYQYLDDCYYYDAZDCYMZYDLZFFFMMY" +
        "CQCWZZMABTBYCTDMNDZGGDFTYPCGQYTTSSFFWBDTZQSSYSTWJJHJYTSXXYLBYQHWWHXEZXWZNNQZJZJJQJCCCHYYXBZXCCYJTLLCQXKNJYCYYCYNZZQYYOEWYCZDCJYC" +
        "CHYJLBTZKYCQWLPGPYLLGKDLDLGKGQBGYCHJXY####Z#W###Z####S#####L#######SL##Z####LGTM####GD#####################ATN##HBLTDZLATMMBJ#LX";

        // Two-character phrase overrides cover context-sensitive leading polyphones.
        private const string PolyphonicPrefixes =
        "万俟M乐器Y乐团Y乐坛Y乐官Y乐工Y乐师Y乐府Y乐律Y乐感Y乐户Y乐手Y乐曲Y乐歌Y乐毅Y乐池Y乐清Y乐理Y乐章Y乐舞Y乐谱Y乐迷Y乐队Y乐音Y乘舆S乜斜N仇姓Q仿徨P会计K传略Z传记Z伺弄S" +
        "伺机S伺瑕S伺隙S伽利J伽蓝Q侧歪Z便佞P便嬖P便宜P俟河S倘佯C傀儡K傍若P免麻W冯河P刨冰B刨刀B刨子B刨平B刨床B刨木B刨花B刹时C刹那C剿袭C剿说C匙子C单于C单姓S卡具Q卡壳Q卡子Q" +
        "卡脖Q厦门X参商S参回S参横S参茸S参辰S叨光T叨在T叨扰T叨拢T叨陪T叶韵X吁天Y吁求Y吁请Y吖啶A否去P否往P否极P否终P呲牙Z呵叻K呷醋X咖喱G咯血K咳咳H咳声H喔喔W嗒丧T嗒然T嘲哳Z" +
        "噱头X囤积T囤聚T圈牢J圩场X大璞T奇偶J奇函J奇数J奇零J宿水X宿雨X射干Y将伯Q将将Q将进Q尉犁Y尉迟Y尿泡S尿脬S屏住B屏声B屏弃B屏息B屏气B屏迹B屏退B屏除B属垣Z属意Z属文Z属望Z" +
        "属毛Z属词Z属辞Z岂弟K巷道H弄口L弄堂L弹丝T弹丸T弹冠T弹剑T弹力T弹劾T弹射T弹性T弹指T弹斤T弹琴T弹空T弹簧T弹腿T弹词T弹跳T弹钢T强嘴J恶不W恶居W恶恶W恶湿W恶紫W恶醉W扁舟P" +
        "扒手P扒灰P扒窃P扒粪P扒糕P扒耳P扒草P扒鸡P扛鼎G扞格H折堕S折本S折秤S折箭S折耗S折腰S拗不N挟主J捰袖L提溜D提防D揭衣Q擿埴Z擿植Z攒三C攒动C攒射C攒盒C攒眉C攒聚C攒锋C攒集C" +
        "攒零C於菟W暴晒P暴腮P暴衣P曝光B曾不Z曾参Z曾孙Z曾母Z曾祖Z朝三Z朝不Z朝乾Z朝云Z朝令Z朝会Z朝前Z朝升Z朝华Z朝发Z朝夕Z朝夷Z朝奏Z朝思Z朝成Z朝折Z朝攀Z朝斯Z朝日Z朝晖Z朝暮Z" +
        "朝更Z朝朝Z朝梁Z朝欢Z朝歌Z朝气Z朝生Z朝种Z朝秦Z朝穿Z朝经Z朝荣Z朝衣Z朝趁Z朝过Z朝钟Z朝锺Z朝闻Z朝阳Z朝霞Z朝露Z朝饔Z朝齑Z期年J枞阳Z枸橼J查查Z栅极S栖栖X校准J校勘J校场J" +
        "校对J校改J校本J校样J校核J校正J校注J校点J校短J校订J校阅J校验J椎髻Z楛耘K槛花J欹嵚Q沈博C沓冈T沓子T沓来T泊位B泊车B泌阳B浒墅X涡河G溃脓H漯河T澄沙D澄结D澹台T炰鳖F犍为Q" +
        "狧穅S率以S率先S率兽S率军S率土S率尔S率性S率然S率由S率直S率真S率队S率领S率马S畜产X畜养X畜妻X畜牧X番禺P疟子Y盛器C盛水C盛菜C盛饭C省亲X省墓X省察X省悟X省视X瞿然J磅礴P" +
        "禅让S秘鲁B稽首Q粘合N粘土N粘液N粘稠N粘结N系好J系带J系泊J系紧J系绳J系鞋J纤夫Q纤手Q纤绳Q纶巾G给与J给予J给付J给体J给养J给水J耙子P腌臜A腌臢A膀胱P膻中D臭味X般桓P芥蓝G" +
        "苕帚T苣卖Q苣荬Q茄子Q茜茜X荤粥X莘庄X莞尔W莞莞W蔚县Y藏人Z藏历Z藏府Z藏戏Z藏族Z藏獒Z藏红Z藏药Z藏蓝Z藏青Z藏香Z虾蟆H蛤粉G蛤蚌G蛤蚧G蛤蜊G行业H行东H行伍H行会H行列H行号H" +
        "行家H行市H行帮H行当H行情H行栈H行款H行行H行规H行话H行货H行距H行辈H行道H行长H行间H被发P被山P被甲P被褐P袷袢Q裨将P裳裳C褎然Y褚小Z见素X解数X解池X解法X调三T调丝T调人T" +
        "调价T调侃T调停T调光T调养T调准T调制T调剂T调匀T调协T调合T调味T调和T调唆T调唇T调嘴T调墨T调处T调幅T调弄T调息T调情T调戏T调护T调控T调摄T调教T调整T调料T调朱T调档T调正T" +
        "调治T调温T调焦T调理T调皮T调神T调笑T调级T调经T调羹T调脂T调舌T调良T调色T调节T调解T调词T调试T调调T调谐T调谑T调资T调适T调音T调频T调风T贾人G贾用G贾祸G贾贸G贾马G车马J" +
        "轧机Z轧账G轧辊Z轧钢Z辗转Z辟举B辟书B辟召B辟引B辟谷B辟邪B遗使W遗劳W重三C重九C重作C重修C重光C重关C重兴C重出C重印C重叠C重合C重启C重唱C重围C重圆C重圭C重垣C重复C重头C" +
        "重奏C重婚C重孙C重审C重山C重岩C重峦C重庆C重床C重建C重张C重弹C重影C重手C重拍C重振C重提C重播C重操C重数C重整C重新C重明C重映C重沓C重洋C重温C重演C重熙C重版C重犯C重现C" +
        "重珪C重理C重生C重申C重睹C重纰C重纸C重组C重聚C重获C重葩C重行C重裀C重见C重规C重译C重读C重起C重足C重蹈C重返C重迭C重述C重迹C重选C重逢C重重C重金C重铬C重门C重阳C重霄C" +
        "铅山Y铤而T镐京H长七C长久C长乐C长于C长亭C长假C长兴C长剑C长卷C长发C长句C长号C长叹C长吁C长吟C长命C长啸C长嘘C长圆C长坂C长城C长处C长夏C长夜C长天C长存C长安C长寿C长局C" +
        "长崎C长川C长工C长年C长庚C长度C长廊C长往C长征C长念C长性C长恨C长恶C长戟C长才C长拳C长揖C长斋C长方C长明C长春C长期C长机C长材C长条C长枕C长林C长枪C长款C长歌C长此C长毛C" +
        "长汀C长江C长沙C长河C长治C长法C长波C长活C长流C长物C长生C长白C长目C长眠C长矛C长短C长石C长程C长空C长笛C长策C长算C长篇C长线C长绒C长统C长绳C长编C长缨C长臂C长舌C长虑C" +
        "长虫C长虹C长蛇C长街C长衣C长衫C长袍C长袖C长袜C长裤C长褂C长计C长诗C长话C长调C长谈C长足C长跑C长跪C长辔C长辞C长远C长途C长逝C长镜C长长C长门C长队C长随C长青C长音C长项C" +
        "长颈C长风C长驱C长驾C长鸣C长鼓C长龙C阿世E阿党E阿其E阿弥E阿意E阿房E阿时E阿胶E阿谀E阿附E陂陀P降伏X降妖X降服X降顺X降龙X靓丽L靓仔L靓女L颉颃X颤栗Z骠勇P骠骑P鸟闹D鹄峙H" +
        "麇至Q龈齿Y龈龈Y龟兹Q龟裂J";
        private static readonly Dictionary<int, char> PolyphonicInitials =
            CreatePolyphonicInitials();

        public static string NormalizeSelection(string value)
        {
            string normalized = string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim().ToUpperInvariant();
            if (normalized == All || normalized == Other)
            {
                return normalized;
            }

            return normalized.Length == 1
                && normalized[0] >= 'A'
                && normalized[0] <= 'Z'
                    ? normalized
                    : null;
        }

        public static bool Matches(JellyfinItem item, string selection)
        {
            string normalized = NormalizeSelection(selection);
            if (item == null || normalized == null)
            {
                return false;
            }
            if (normalized == All)
            {
                return true;
            }

            char expected = normalized[0];
            return InitialFor(item.Name) == expected
                || InitialFor(item.OriginalTitle) == expected
                || InitialFor(item.SortName) == expected;
        }

        public static char InitialFor(string title)
        {
            if (string.IsNullOrWhiteSpace(title))
            {
                return '\0';
            }

            string normalized = title.Normalize(NormalizationForm.FormKD);
            for (int index = 0; index < normalized.Length; index++)
            {
                char character = normalized[index];
                UnicodeCategory category = CharUnicodeInfo.GetUnicodeCategory(character);
                if (category == UnicodeCategory.NonSpacingMark
                    || category == UnicodeCategory.SpacingCombiningMark
                    || category == UnicodeCategory.EnclosingMark
                    || char.IsWhiteSpace(character)
                    || char.IsPunctuation(character)
                    || char.IsSymbol(character))
                {
                    continue;
                }

                if (character >= 'A' && character <= 'Z')
                {
                    return character;
                }
                if (character >= 'a' && character <= 'z')
                {
                    return char.ToUpperInvariant(character);
                }
                if (character >= HanStart && character < HanEndExclusive)
                {
                    char contextual = PolyphonicInitialFor(normalized, index);
                    if (contextual != (char)0)
                    {
                        return contextual;
                    }
                    return HanInitials[character - HanStart];
                }
                if (char.IsDigit(character) || char.IsLetter(character))
                {
                    return Other[0];
                }
            }

            return '\0';
        }

        private static char PolyphonicInitialFor(string value, int index)
        {
            if (index < 0 || index + 1 >= value.Length)
            {
                return (char)0;
            }

            int key = value[index] << 16 | value[index + 1];
            char initial;
            return PolyphonicInitials.TryGetValue(key, out initial)
                ? initial
                : (char)0;
        }

        private static Dictionary<int, char> CreatePolyphonicInitials()
        {
            Dictionary<int, char> initials = new Dictionary<int, char>(
                PolyphonicPrefixes.Length / 3);
            for (int index = 0; index + 2 < PolyphonicPrefixes.Length; index += 3)
            {
                int key = PolyphonicPrefixes[index] << 16
                    | PolyphonicPrefixes[index + 1];
                initials[key] = PolyphonicPrefixes[index + 2];
            }
            return initials;
        }
    }
}
